blockbuster/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("main.urls")),
    path("auth/", include("authentication.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create_item, name='create'),
    path('show/xml/', views.show_xml, name='show_xml'),
    path('show/json/', views.show_json, name='show_json'),
    path('show/xml/<int:id>/', views.show_xml_by_id, name='show_xml_by_id'),
    path('show/json/<int:id>/', views.show_json_by_id, name='show_json_by_id'),
    path('register/', views.register, name='register'),
    path('login/', views.login_user, name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('item/add/<int:id>/', views.add_amount, name='add_amount'),
    path('item/reduce/<int:id>/', views.reduce_amount, name='reduce_amount'),
    path('item/delete/<int:id>/', views.delete_item, name='delete_item'),
    path('get-item-json/', views.get_item_json, name='get_item_json'),
    path('create-ajax/', views.create_ajax, name='create_ajax'),
    path('delete-ajax/<int:id>/', views.delete_ajax, name='delete_ajax'),
    path('create-flutter/', views.create_flutter, name='create_flutter'),
]

main/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Item(models.Model):
    name = models.CharField(max_length=255)
    amount = models.IntegerField()
    description = models.TextField()
    price = models.FloatField()
    year = models.IntegerField()
    genre = models.CharField(max_length=255)
    duration = models.IntegerField()
    rating = models.FloatField()
    image = models.ImageField(upload_to='images/')
    user = models.ForeignKey(User, on_delete=models.CASCADE)

main/forms.py
from django.forms import ModelForm
from main.models import Item

class ItemForm(ModelForm):
    class Meta:
        model = Item
        fields = ['name', 'amount', 'description', 'price', 'year', 'genre', 'duration', 'rating', 'image', 'user']

main/views.py
from django.shortcuts import render, redirect
from .models import Item
from .forms import ItemForm
from django.http import HttpResponse, HttpResponseForbidden, HttpResponseNotFound, JsonResponse
from django.core import serializers
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib import messages
from django.contrib.auth import login, logout
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
from datetime import datetime


# Create your views here.
def index(request):
    if request.user.is_authenticated:
        items = Item.objects.filter(user=request.user)
    else:
        items = []
    context = {
        "items": items,
        "user": request.user if request.user.is_authenticated else "",
    }
    response = render(request, 'index.html', context)
    if request.COOKIES.get('last_login'):
        response.set_cookie('last_login', request.COOKIES.get('last_login'))
    return response

@login_required(login_url='main:login')
def create_item(request):
    if request.method == 'POST':
        data = request.POST.copy()
        data['user'] = request.user.id
        files = request.FILES.copy()
        form = ItemForm(data, files)
        print(form.errors)
        if form.is_valid():
            form.save()
            return redirect('main:index')
    return render(request, 'form.html')

def show_xml(request):
    items = Item.objects.all()
    data = serializers.serialize('xml', items)
    return HttpResponse(data, content_type='application/xml')

def show_json(request):
    items = Item.objects.all()
    data = serializers.serialize('json', items)
    return HttpResponse(data, content_type='application/json')

def show_xml_by_id(request, id):
    item = Item.objects.get(id=id)
    data = serializers.serialize('xml', [item])
    return HttpResponse(data, content_type='application/xml')

def show_json_by_id(request, id):
    item = Item.objects.get(id=id)
    data = serializers.serialize('json', [item])
    return HttpResponse(data, content_type='application/json')

def register(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f'Account created for {username}!')
            return redirect('main:login')
    context = {
        'form': UserCreationForm(),
    }
    return render(request, 'register.html', context)

def login_user(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            login(request, form.get_user())
            username = form.cleaned_data.get('username')
            messages.success(request, f'Welcome {username}!')
            response = redirect('main:index')
            response.set_cookie('last_login', str(datetime.now()))
            return response
    context = {
        'form': AuthenticationForm(),
    }
    return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    response = redirect('main:index')
    response.delete_cookie('last_login')
    return response

@login_required(login_url='main:login')
def add_amount(request, id):
    item = Item.objects.get(id=id)
    if request.user == item.user:
        item.amount += 1
        item.save()
    return redirect('main:index')

@login_required(login_url='main:login')
def reduce_amount(request, id):
    item = Item.objects.get(id=id)
    if request.user == item.user:
        if item.amount > 0:
            item.amount -= 1
            item.save()
        else:
            item.delete()
    return redirect('main:index')

@login_required(login_url='main:login')
def delete_item(request, id):
    item = Item.objects.get(id=id)
    if request.user == item.user:
        item.delete()
    return redirect('main:index')

@login_required(login_url='main:login')
def get_item_json(request):
    items = Item.objects.filter(user=request.user)
    data = serializers.serialize('json', items)
    return HttpResponse(data)

@login_required(login_url='main:login')
@csrf_exempt
def create_ajax(request):
    if request.method == 'POST':
        new_item = Item(
            name=request.POST.get('name'),
            amount=request.POST.get('amount'),
            description=request.POST.get('description'),
            price=request.POST.get('price'),
            year=request.POST.get('year'),
            genre=request.POST.get('genre'),
            duration=request.POST.get('duration'),
            rating=request.POST.get('rating'),
            image=request.FILES.get('image'),
            user=request.user
        )
        new_item.save()

        return HttpResponse('Item added', status=201)
    return HttpResponseNotFound()

@login_required(login_url='main:login')
@csrf_exempt
def delete_ajax(request, id):
    if request.method == 'DELETE':
        item = Item.objects.get(id=id)
        if item.user == request.user:
            item.delete()
            return HttpResponse('Item deleted', status=204)

        return HttpResponseForbidden()
    return HttpResponseNotFound()

@login_required(login_url='main:login')
@csrf_exempt
def create_flutter(request):
    if request.method == 'POST':
        new_item = Item(
            name=request.POST.get('name'),
            amount=request.POST.get('amount'),
            description=request.POST.get('description'),
            price=request.POST.get('price'),
            year=request.POST.get('year'),
            genre=request.POST.get('genre'),
            duration=request.POST.get('duration'),
            rating=request.POST.get('rating'),
            image=request.FILES.get('image'),
            user=request.user
        )
        new_item.save()

        return JsonResponse({'status': True}, status=201)
    return HttpResponseNotFound()

main/templates/form.html

{% extends 'base.html' %}

{% block meta %}
    <title>Blockbuster</title>
{% endblock meta %}

{% block content %}
    <section class="vh-100">
        <div class="row d-flex justify-content-center align-items-center h-100">
            <div class="col-12 col-md-8 col-lg-6 col-xl-5">
                <div class="container-fluid mt-5">
                    <div class="row">
                        <div class="col-12">
                            <h1 class="text-center" style="color: #F2BED1;">Blockbuster</h1>
                        </div>
                    </div>
                </div>
              <div class="card text-white" style="border-radius: 1rem; background-color: #F2BED1;">
                <div class="card-body p-5 text-center">
      
                  <form class="mb-md-5 mt-md-4" method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
      
                    <h2 class="fw-bold mb-4 text-uppercase">Add Movie</h2>
      
                    <div class="form-outline form-white mb-4">
                        <label class="form-label" for="name">Name</label>
                      <input type="text" name="name" required id="name" class="form-control form-control-lg" />
                    </div>
      
                    <div class="form-outline form-white mb-4">
                        <label class="form-label" for="amount">Amount</label>
                      <input type="number" name="amount" required id="amount" class="form-control form-control-lg" />
                    </div>
      
                    <div class="form-outline form-white mb-4">
                        <label class="form-label" for="description">Description</label>
                      <textarea name="description" required id="description" class="form-control form-control-lg" rows="4"></textarea>
                    </div>
      
                    <div class="form-outline form-white mb-4">
                        <label class="form-label" for="price">Price</label>
                      <input type="number" name="price" required id="price" class="form-control form-control-lg" />
                    </div>
      
                    <div class="form-outline form-white mb-4">
                        <label class="form-label" for="year">Year</label>
                      <input type="number" name="year" required id="year" class="form-control form-control-lg" />
                    </div>
      
                    <div class="form-outline form-white mb-4">
                        <label class="form-label" for="genre">Genre</label>
                      <input type="text" name="genre" required id="genre" class="form-control form-control-lg" />
                    </div>
      
                    <div class="form-outline form-white mb-4">
                        <label class="form-label" for="duration">Duration</label>
                      <input type="number" name="duration" required id="duration" class="form-control form-control-lg" />
                    </div>
      
                    <div class="form-outline form-white mb-4">
                        <label class="form-label" for="rating">Rating</label>
                      <input type="number" name="rating" required id="rating" class="form-control form-control-lg" step="0.1" />
                    </div>
      
                    <div class="form-outline form-white mb-4">
                        <label class="form-label" for="image">Image</label>
                      <input type="file" name="image" accept="image/*" required id="image" class="form-control form-control-lg" />
                    </div>

                    <button class="btn btn-outline-light btn-lg px-5" type="submit">Add</button>
      
                  </form>
                  {% if messages %}
                    {% for message in messages %}
                        {% if message.tags == 'error' %}
                            <div class="alert alert-danger" role="alert">
                                {{ message }}
                            </div>
                        {% else %}
                            <div class="alert alert-success" role="alert">
                                {{ message }}
                            </div>
                        {% endif %}
                    {% endfor %}
                  {% endif %}
                </div>
              </div>
            </div>
        </div>
    </section>
{% endblock content %}

main/templates/index.html
{% extends 'base.html' %}

{% block meta %}
    <title>Blockbuster</title>
{% endblock meta %}

{% block content %}
<section class="text-center">
    <div class="container pt-5">
        <h1 style="color: #F2BED1">Blockbuster</h1>
        <h3>Movie Database</h3>
        <p class="lead text-muted"> This is a simple movie database where you can add and delete for movies. </p>
        <p>
            {% if user.is_authenticated %}
                <p class="lead text-muted">Username: {{ user.username }}<br/>
                Last Login: {{ request.COOKIES.last_login }}</p>
                <a href="{% url 'main:create' %}" class="btn btn-outline-dark my-2">Create Item</a>
                <a href="{% url 'main:logout' %}" class="btn btn-outline-secondary my-2">Logout</a>
            {% else %}
                <a href="{% url 'main:register' %}" class="btn btn-outline-dark my-2">Register</a>
                <a href="{% url 'main:login' %}" class="btn btn-outline-secondary my-2">Login</a>
            {% endif %}
        </p>
    </div>
</section>
{% if user.is_authenticated %}
    <section id="items"></section>
    <button type="button" class="btn btn-outline-dark" data-bs-toggle="modal" data-bs-target="#modalItem" style="position: fixed; bottom: 2rem; right: 2rem; border-radius: 1rem;">Add Movie</button>

    <div class="modal modal-lg fade" id="modalItem" tabindex="-1" aria-labelledby="modalItemLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content text-center text-white" style="border-radius: 1rem; background-color: #F2BED1;">
                <div class="modal-header">
                    <h5 class="modal-title" id="modalItemLabel" style="color: #B0578D;">Add Movie</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close" style="color: #B0578D;"></button>
                </div>
                <div class="modal-body">
                    <form id="createItemForm" onsubmit="return false;">
                        {% csrf_token %}
                        <div class="form-outline form-white mb-4">
                            <label class="form-label" for="name">Name</label>
                        <input type="text" name="name" required id="name" class="form-control form-control-lg" />
                        </div>
        
                        <div class="form-outline form-white mb-4">
                            <label class="form-label" for="amount">Amount</label>
                        <input type="number" name="amount" required id="amount" class="form-control form-control-lg" />
                        </div>
        
                        <div class="form-outline form-white mb-4">
                            <label class="form-label" for="description">Description</label>
                        <textarea name="description" required id="description" class="form-control form-control-lg" rows="4"></textarea>
                        </div>
        
                        <div class="form-outline form-white mb-4">
                            <label class="form-label" for="price">Price</label>
                        <input type="number" name="price" required id="price" class="form-control form-control-lg" />
                        </div>
        
                        <div class="form-outline form-white mb-4">
                            <label class="form-label" for="year">Year</label>
                        <input type="number" name="year" required id="year" class="form-control form-control-lg" />
                        </div>
        
                        <div class="form-outline form-white mb-4">
                            <label class="form-label" for="genre">Genre</label>
                        <input type="text" name="genre" required id="genre" class="form-control form-control-lg" />
                        </div>
        
                        <div class="form-outline form-white mb-4">
                            <label class="form-label" for="duration">Duration</label>
                        <input type="number" name="duration" required id="duration" class="form-control form-control-lg" />
                        </div>
        
                        <div class="form-outline form-white mb-4">
                            <label class="form-label" for="rating">Rating</label>
                        <input type="number" name="rating" required id="rating" class="form-control form-control-lg" step="0.1" />
                        </div>
        
                        <div class="form-outline form-white mb-4">
                            <label class="form-label" for="image">Image</label>
                        <input type="file" name="image" accept="image/*" required id="image" class="form-control form-control-lg" />
                        </div>

                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-outline-secondary" data-bs-dismiss="modal">Close</button>
                    <button type="button" class="btn btn-outline-dark" id="createItem" data-bs-dismiss="modal">Create</button>
                </div>
            </div>
        </div>
    </div>
{% endif %}
{% endblock content %}

{% block script %}
    {% if user.is_authenticated %}
    <script>
        async function getItems() {
            return fetch("{% url 'main:get_item_json' %}")
                .then(response => response.json())
        }

        async function refreshItems() {
            document.getElementById("items").innerHTML = ""
            const items = await getItems()
            const length = Object.keys(items).length
            let html = '<div class="container">'
            html += '<p class="lead text-muted">Total Item: ' + length + '</p>'
            html += '<div class="row row-cols-3">';
            items.forEach((item) => {
                html += '<div class="col-md-6 col-lg-4 mb-5">'
                html += '<div class="card text-white" style="border-radius: 1rem; background-color: #F2BED1;">'
                html += '<img src="/media/' + item.fields.image + '" class="card-img-top" alt="Image" style="border-radius: 1rem 1rem 0 0;">'
                html += '<div class="card-body">'
                html += '<h5 class="card-title" style="color: #B0578D">' + item.fields.name + '</h5>'
                html += '<p class="card-text">' + item.fields.description + '</p>'
                html += '<p class="card-text">Amount: ' + item.fields.amount + '</p>'
                html += '<p class="card-text">Price: ' + item.fields.price + '</p>'
                html += '<p class="card-text">Year: ' + item.fields.year + '</p>'
                html += '<p class="card-text">Genre: ' + item.fields.genre + '</p>'
                html += '<p class="card-text">Duration: ' + item.fields.duration + '</p>'
                html += '<p class="card-text" style="color: #EBE76C;"><b>Rating: ' + item.fields.rating + '</b></p>'
                html += '<a href="/item/add/' + item.pk + '" class="btn btn-outline-dark mx-2">Add</a>'
                html += '<a href="/item/reduce/' + item.pk + '" class="btn btn-outline-secondary mx-2">Reduce</a>'
                html += '<button type="button" class="btn btn-outline-danger mx-2" onclick="deleteItem(' + item.pk + ')">Delete</button>'
                html += '</div>'
                html += '</div>'
                html += '</div>'
            })
            html += '</div>'
            html += '</div>'
            document.getElementById("items").innerHTML = html
        }

        refreshItems();
        
        function createItem() {
            fetch("{% url 'main:create_ajax' %}", {
                method: "POST",
                body: new FormData(document.getElementById("createItemForm"))
            }).then(() => {
                refreshItems()
            })

            document.getElementById("createItemForm").reset()
            return false
        }

        document.getElementById("createItem").onclick = createItem

        function deleteItem(id) {
            fetch("{% url 'main:delete_ajax' 0 %}".replace("0", id), {
                method: "DELETE",
            }).then(() => {
                refreshItems()
            })

            return false
        }

    </script>
    {% endif %}
{% endblock script %}

main/templates/login.html
{% extends 'base.html' %}

{% block meta %}
    <title>Blockbuster</title>
{% endblock meta %}

{% block content %}
    <section class="vh-100">
        <div class="row d-flex justify-content-center align-items-center h-100">
            <div class="col-12 col-md-8 col-lg-6 col-xl-5">
                <div class="container-fluid mt-5">
                    <div class="row">
                        <div class="col-12">
                            <h1 class="text-center" style="color: #F2BED1;">Blockbuster</h1>
                        </div>
                    </div>
                </div>
              <div class="card text-white" style="border-radius: 1rem; background-color: #F2BED1;">
                <div class="card-body p-5 text-center">
      
                  <form class="mb-md-5 mt-md-4 pb-5" method="POST">
                    {% csrf_token %}
      
                    <h2 class="fw-bold mb-4 text-uppercase">Login</h2>
      
                    <div class="form-outline form-white mb-4">
                        <label class="form-label" for="username">Username</label>
                      <input type="text" name="username" required id="username" class="form-control form-control-lg" />
                    </div>
      
                    <div class="form-outline form-white mb-4">
                        <label class="form-label" for="password">Password</label>
                      <input type="password" name="password" required id="password" class="form-control form-control-lg" />
                    </div>

                    <button class="btn btn-outline-light btn-lg px-5" type="submit">Login</button>
      
                  </form>
                  {% if messages %}
                    {% for message in messages %}
                        {% if message.tags == 'error' %}
                            <div class="alert alert-danger" role="alert">
                                {{ message }}
                            </div>
                        {% else %}
                            <div class="alert alert-success" role="alert">
                                {{ message }}
                            </div>
                        {% endif %}
                    {% endfor %}
                  {% endif %}
                  <div>
                    <p class="mb-0">Don't have an account? <a href="{% url "main:register" %}" class="text-white-50 fw-bold">Sign Up</a></p>
                  </div>
                </div>
              </div>
            </div>
        </div>
    </section>
    
{% endblock content %}

main/templates/register.html
{% extends 'base.html' %}

{% block meta %}
    <title>Blockbuster</title>
{% endblock meta %}

{% block content %}
<section class="vh-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col-12 col-md-8 col-lg-6 col-xl-5">
            <div class="container-fluid mt-5">
                <div class="row">
                    <div class="col-12">
                        <h1 class="text-center" style="color: #F2BED1;">Blockbuster</h1>
                    </div>
                </div>
            </div>
          <div class="card text-white" style="border-radius: 1rem; background-color: #F2BED1;">
            <div class="card-body p-5 text-center">
  
              <form class="mb-md-5 mt-md-4 pb-5" method="POST">
                {% csrf_token %}
  
                <h2 class="fw-bold mb-4 text-uppercase">Register</h2>
  
                <div class="form-outline form-white mb-4">
                    <label class="form-label" for="username">Username</label>
                  <input type="text" name="username" required id="username" class="form-control form-control-lg" />
                </div>
  
                <div class="form-outline form-white mb-4">
                    <label class="form-label" for="password1">Password</label>
                  <input type="password" name="password1" required id="password1" class="form-control form-control-lg" />
                </div>
  
                <div class="form-outline form-white mb-4">
                    <label class="form-label" for="password2">Password Confirmation</label>
                  <input type="password" name="password2" required id="password2" class="form-control form-control-lg" />
                </div>

                <button class="btn btn-outline-light btn-lg px-5" type="submit">Register</button>
  
              </form>
              {% if messages %}
                {% for message in messages %}
                    {% if message.tags == 'error' %}
                        <div class="alert alert-danger text-white" role="alert">
                            <p>{{ message }}</p>
                        </div>
                    {% else %}
                        <div class="alert alert-success text-white" role="alert">
                            <p>{{ message }}</p>
                        </div>
                    {% endif %}
                {% endfor %}
              {% endif %}
              <div>
                <p class="mb-0">Have an account already? <a href="{% url "main:login" %}" class="text-white-50 fw-bold">Login</a></p>
              </div>
            </div>
          </div>
        </div>
    </div>
</section>
{% endblock content %}